services:
  - type: web
    name: telegram-forward-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python3 main.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SOURCE_CHAT_ID
        sync: false
      - key: DEST_CHAT_ID
        sync: false
